<?php

declare(strict_types=1);

namespace Wbc\CareersBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\CoreBundle\Form\Type\DatePickerType;
use Sonata\CoreBundle\Form\Type\DateTimePickerType;
use Sonata\FormatterBundle\Form\Type\SimpleFormatterType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Wbc\CareersBundle\Entity\Role;

/**
 * Class RoleAdmin.
 *
 * @author Majid Mvulle <majid@majidmvulle.com>
 */
class RoleAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $form): void
    {
        $form->add('title')
            ->add('department', ChoiceType::class, ['choices' => Role::getDepartments()])
            ->add('location', ChoiceType::class, [
                'choices' => Role::getCities(),
            ])
            ->add('description', SimpleFormatterType::class, [
                'format' => 'richhtml',
                'ckeditor_context' => 'default',
                'required' => false,
            ])
            ->add('responsibilities', SimpleFormatterType::class, [
                'format' => 'richhtml',
                'ckeditor_context' => 'default',
                'required' => false,
            ])
            ->add('skillsAndExperience', SimpleFormatterType::class, [
                'format' => 'richhtml',
                'ckeditor_context' => 'default',
                'required' => false,
            ])
            ->add('publishAt', DateTimePickerType::class)
            ->add('expiresAt', DatePickerType::class, ['required' => false])
            ->add('isActive')
        ;
    }

    protected function configureListFields(ListMapper $list): void
    {
        $list->addIdentifier('id')
            ->add('title')
            ->add('department', 'choice', ['choices' => Role::getDepartments()])
            ->add('location', 'choice', ['choices' => Role::getCities()])
            ->add('publishAt')
            ->add('expiresAt')
            ->add('isActive', 'boolean', ['editable' => true, 'label' => 'Active'])
            ->add('totalCandidates')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('_action', null, ['actions' => ['show' => [], 'edit' => []]])
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $filter): void
    {
        parent::configureDatagridFilters($filter); // TODO: Change the autogenerated stub
    }

    protected function configureShowFields(ShowMapper $show): void
    {
        parent::configureShowFields($show); // TODO: Change the autogenerated stub
    }

    protected function configureRoutes(RouteCollection $collection): void
    {
        $collection->remove('delete');
    }
}
