imports:
    - { resource: parameters.yml }
    - { resource: sonata.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: ivory/ivory_ckeditor.yml }

parameters:
    locale: en
    craue_config.cache_adapter.class: Craue\ConfigBundle\CacheAdapter\DoctrineCacheBundleAdapter
    craue_config.redirectRouteAfterModify: sonata_admin_dashboard

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        cookie_lifetime: 604800
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
        - '@SonataFormatter/Form/formatter.html.twig'
    globals:
        site_domain: "%site_domain%"
        site_email: "%site_email%"
        site_title: "%site_title%"
        site_phone: "%site_phone%"
        company_name: "%company_name%"
        company_office_number: "%company_office_number%"
        company_office_building: "%company_office_building%"
        company_office_street: "%company_office_street%"
        company_po_box: "%company_po_box%"
        company_office_phone: "%company_office_phone%"
        site_menu: "%site_menu%"
        site_facebook: "%site_facebook%"
        site_instagram: "%site_instagram%"
        site_twitter: "%site_twitter%"
        site_linkedin: "%site_linkedin%"
        google_maps_api_key: "%google_maps_api_key%"
        initial_total_appointments: "%initial_total_appointments%"
        from_email: "%from_email%"
        from_sender_name: "%from_sender_name%"
        tech_email: "%tech_email%"
        google_reviews_url: "%google_reviews_url%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
#    bundles:        [ JbmcListingBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
            jsqueeze: ~
        jsqueeze: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType
            branch_object:  Wbc\BranchBundle\Doctrine\DBAL\Types\BranchType
            branch_timing_object: Wbc\BranchBundle\Doctrine\DBAL\Types\TimingType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            ApplicationSonataMediaBundle: ~
            SonataMediaBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

## FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Wbc\UserBundle\Entity\User
    from_email:
        address: "%from_email%"
        sender_name: "%from_sender_name%"
#    registration:
#        form:
#           type: Jbmc\UserBundle\Form\RegistrationType

# JMS Di Extra Configuration
jms_di_extra:
    disable_grep: true
    locations:
        all_bundles: true #performance issue, set this to false and define bundles below
        directories: ["%kernel.root_dir%/../src"]

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: "%kernel.root_dir%/serializer/FOSUB"

lexik_maintenance:
    authorized:
        ips: "%lexik_ips%"
    response:
        code: 503
        status: "Website under maintenance. Please try again later."
    driver:
        class: '\Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver'
        options: {file_path: "%kernel.root_dir%/cache/lock"}

doctrine_cache:
  providers:
    craue_config_cache:
      apc: ~
      namespace: craue_config
      aliases:
        - craue_config_cache_provider

sonata_media:
    # if you don't use default namespace configuration
    #class:
    #    media: MyVendor\MediaBundle\Entity\Media
    #    gallery: MyVendor\MediaBundle\Entity\Gallery
    #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
    db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
    default_context: default # you need to set a context
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 555, quality: 95}
                big:   { width: 847, quality: 90}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

    providers:
        image:
            resizer: sonata.media.resizer.square

knp_paginator:
    page_range: 5                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template
