imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: sonata.yml }
    - { resource: doctrine_extensions.yml }

parameters:
    locale: en

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
        - 'SonataCoreBundle:Form:datepicker.html.twig'
    globals:
        site_title: "%site_title%"
        site_phone: "%site_phone%"
        company_name: "%company_name%"
        company_office_number: "%company_office_number%"
        company_office_building: "%company_office_building%"
        company_office_street: "%company_office_street%"
        site_menu: "%site_menu%"
        site_facebook: "%site_facebook%"
        site_instagram: "%site_instagram%"
        site_twitter: "%site_twitter%"
        site_linkedin: "%site_linkedin%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: "%kernel.debug%"
#    bundles:        [ JbmcListingBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
            formatter: "Leafo\ScssPhp\Formatter\Compressed"
            jsqueeze: ~
        jsqueeze: "PatchWork\JSqueeze"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
        types:
            json: Sonata\Doctrine\Types\JsonType
            branch_object:  Wbc\BranchBundle\Doctrine\DBAL\Types\BranchType
            branch_timing_object: Wbc\BranchBundle\Doctrine\DBAL\Types\TimingType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

#doctrine_mongodb:
#    connections:
#        default:
#            server: "%mongodb_server%"
#            options: {}
#    default_database: jbmc_sf
#    document_managers:
#        default:
#            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine Migrations Configuration
doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

## FOS User Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Wbc\UserBundle\Entity\User
    from_email:
        address: "donotreply@webuycarsdxb.com"
        sender_name: "WeBuyCarsDXB"
#    registration:
#        form:
#           type: Jbmc\UserBundle\Form\RegistrationType

# JMS Di Extra Configuration
jms_di_extra:
    disable_grep: true
    locations:
        all_bundles: true #performance issue, set this to false and define bundles below
        directories: ["%kernel.root_dir%/../src"]

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUB:
                namespace_prefix: FOS\UserBundle
                path: %kernel.root_dir%/serializer/FOSUB
