# services to handle doctrine extensions
# import it in config.yml

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine_mongodb.odm.event_subscriber }
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]
