wbc_used_cars:
    resource: "@WbcUsedCarsBundle/Resources/config/routing.yml"
    prefix:   /used-cars

wbc_careers:
    resource: "@WbcCareersBundle/Resources/config/routing.yml"
    prefix:   /careers

craue_config_settings:
  resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
  prefix: /settings
  schemes: [https]

wbc_vehicle:
    resource: "@WbcValuationBundle/Resources/config/routing.yml"
    schemes: [https]

wbc_valuation:
    resource: "@WbcVehicleBundle/Resources/config/routing.yml"
    prefix:   /vehicles
    schemes: [https]

wbc_branch:
    resource: "@WbcBranchBundle/Resources/config/routing.yml"
    prefix:   /branches
    schemes: [https]

wbc_user:
    resource: "@WbcUserBundle/Resources/config/routing.yml"
    prefix:   /
    schemes: [https]

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    schemes: [https]

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
    schemes: [https]

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
    schemes: [https]

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
    schemes: [https]

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    schemes: [https]

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    schemes: [https]

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    schemes: [https]

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery
    schemes: [https]

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media
    schemes: [https]

wbc_utility:
    resource: "@WbcUtilityBundle/Resources/config/routing.yml"
    prefix:   /
    schemes: [https]

wbc_blog:
    resource: "@WbcBlogBundle/Resources/config/routing.yml"
    prefix:   /blog
    schemes: [https]

wbc_static:
    resource: "@WbcStaticBundle/Resources/config/routing.yml"
    prefix:   /
    schemes: [https]
