security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    access_decision_manager:
        strategy: unanimous

    role_hierarchy:
        ROLE_APPOINTMENT_READER:
            - ROLE_ADMIN_BRANCH_APPOINTMENT_LIST
            - ROLE_ADMIN_BRANCH_APPOINTMENT_VIEW
        ROLE_APPOINTMENT_EDITOR:
            - ROLE_ADMIN_BRANCH_APPOINTMENT_CREATE
            - ROLE_ADMIN_BRANCH_APPOINTMENT_EDIT
        ROLE_APPOINTMENT_ADMIN:
            - ROLE_APPOINTMENT_READER
            - ROLE_APPOINTMENT_EDITOR
            - ROLE_ADMIN_BRANCH_APPOINTMENT_EXPORT
            - ROLE_ADMIN_BRANCH_APPOINTMENT_DELETE
        ROLE_INSPECTION_READER:
            - ROLE_ADMIN_BRANCH_INSPECTION_LIST
            - ROLE_ADMIN_BRANCH_INSPECTION_VIEW
        ROLE_INSPECTION_EDITOR:
            - ROLE_ADMIN_BRANCH_INSPECTION_CREATE
            - ROLE_ADMIN_BRANCH_INSPECTION_EDIT
        ROLE_INSPECTION_ADMIN:
            - ROLE_INSPECTION_READER
            - ROLE_INSPECTION_EDITOR
            - ROLE_ADMIN_BRANCH_INSPECTION_EXPORT
            - ROLE_ADMIN_BRANCH_INSPECTION_DELETE
        ROLE_VALUATION_READER:
            - ROLE_ADMIN_VALUATION_LIST
            - ROLE_ADMIN_VALUATION_VIEW
        ROLE_VALUATION_EDITOR:
            - ROLE_ADMIN_VALUATION_CREATE
            - ROLE_ADMIN_VALUATION_EDIT
        ROLE_VALUATION_ADMIN:
            - ROLE_VALUATION_READER
            - ROLE_VALUATION_EDITOR
            - ROLE_ADMIN_VALUATION_EXPORT
            - ROLE_ADMIN_VALUATION_DELETE
        ROLE_DEAL_READER:
            - ROLE_ADMIN_BRANCH_DEAL_LIST
            - ROLE_ADMIN_BRANCH_DEAL_VIEW
        ROLE_DEAL_EDITOR:
            - ROLE_ADMIN_BRANCH_DEAL_CREATE
            - ROLE_ADMIN_BRANCH_DEAL_EDIT
        ROLE_DEAL_ADMIN:
            - ROLE_DEAL_READER
            - ROLE_DEAL_EDITOR
            - ROLE_ADMIN_BRANCH_DEAL_EXPORT
            - ROLE_ADMIN_BRANCH_DEAL_DELETE
        ROLE_VALUATION_CONFIGURATION_READER:
            - ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_LIST
            - ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_VIEW
        ROLE_VALUATION_CONFIGURATION_EDITOR:
            - ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_CREATE
            - ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_EDIT
        ROLE_VALUATION_CONFIGURATION_ADMIN:
            - ROLE_VALUATION_CONFIGURATION_READER
            - ROLE_VALUATION_CONFIGURATION_EDITOR
            - ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_EXPORT
            - ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_DELETE
        ROLE_ADMIN:           [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_CAREERS_EDITOR:
            - ROLE_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_DELETE
            - ROLE_ADMIN_CAREERS_ROLE_CREATE
            - ROLE_ADMIN_CAREERS_ROLE_LIST
            - ROLE_ADMIN_CAREERS_ROLE_VIEW
            - ROLE_ADMIN_CAREERS_ROLE_EDIT
            - ROLE_ADMIN_CAREERS_CANDIDATE_CREATE
            - ROLE_ADMIN_CAREERS_CANDIDATE_LIST
            - ROLE_ADMIN_CAREERS_CANDIDATE_VIEW
            - ROLE_ADMIN_CAREERS_CANDIDATE_EDIT
        ROLE_BLOG_EDITOR:
            - ROLE_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_DELETE
            - ROLE_ADMIN_BLOG_POST_CREATE
            - ROLE_ADMIN_BLOG_POST_LIST
            - ROLE_ADMIN_BLOG_POST_VIEW
            - ROLE_ADMIN_BLOG_POST_EDIT
            - ROLE_ADMIN_BLOG_CATEGORY_CREATE
            - ROLE_ADMIN_BLOG_CATEGORY_LIST
            - ROLE_ADMIN_BLOG_CATEGORY_VIEW
            - ROLE_ADMIN_BLOG_CATEGORY_EDIT
        ROLE_USED_CARS_EDITOR:
            - ROLE_ADMIN
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_EDIT
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_VIEW
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_LIST
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_CREATE
            - ROLE_SONATA_MEDIA_ADMIN_MEDIA_DELETE
            - ROLE_ADMIN_USED_CARS_ROLE_CREATE
            - ROLE_ADMIN_USED_CARS_ROLE_LIST
            - ROLE_ADMIN_USED_CARS_ROLE_VIEW
            - ROLE_ADMIN_USED_CARS_ROLE_EDIT
            - ROLE_ADMIN_USED_CARS_CANDIDATE_CREATE
            - ROLE_ADMIN_USED_CARS_CANDIDATE_LIST
            - ROLE_ADMIN_USED_CARS_CANDIDATE_VIEW
            - ROLE_ADMIN_USED_CARS_CANDIDATE_EDIT            
        ROLE_APPOINTMENT_SMS: [ROLE_USER]
        ROLE_ACCOUNTANT:
            - ROLE_ADMIN
            - ROLE_APPOINTMENT_READER
            - ROLE_INSPECTION_READER
            - ROLE_DEAL_READER
            - ROLE_ADMIN_BRANCH_DEAL_CREATE
        ROLE_PURCHASING:
            - ROLE_ADMIN
            - ROLE_VALUATION_READER
            - ROLE_APPOINTMENT_READER
            - ROLE_INSPECTION_READER
            - ROLE_INSPECTION_EDITOR
            - ROLE_VALUATION_CONFIGURATION_READER
            - ROLE_VALUATION_CONFIGURATION_EDITOR
        ROLE_CALL_CENTER:
            - ROLE_ADMIN
            - ROLE_VALUATION_READER
            - ROLE_VALUATION_EDITOR
            - ROLE_APPOINTMENT_READER
            - ROLE_APPOINTMENT_EDITOR
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH
            - ROLE_APPOINTMENT_ADMIN
            - ROLE_INSPECTION_ADMIN
            - ROLE_VALUATION_ADMIN
            - ROLE_DEAL_ADMIN
            - ROLE_VALUATION_CONFIGURATION_ADMIN
            - ROLE_BLOG_EDITOR
            - ROLE_ADMIN_BLOG_POST_EXPORT
            - ROLE_ADMIN_BLOG_POST_DELETE
            - ROLE_ADMIN_BLOG_CATEGORY_EXPORT
            - ROLE_ADMIN_BLOG_CATEGORY_DELETE

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                 provider: fos_userbundle
                 csrf_token_generator: security.csrf.token_manager
            anonymous: true
            logout: true

    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
        - { path: ^/settings, roles: ROLE_SUPER_ADMIN }
