sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
sonata_admin:
    dashboard:
        groups:
            Appointments:
                label: Appointments
                items: [admin.branch.appointment]
                roles: [ROLE_APPOINTMENT_READER, ROLE_APPOINTMENT_EDITOR, ROLE_APPOINTMENT_ADMIN]
                on_top: true
                icon:   '<i class="fa fa-calendar-check-o"></i>'
            Inspections:
                label: Inspections
                items: [admin.branch.inspection]
                roles: [ROLE_INSPECTION_READER, ROLE_INSPECTION_EDITOR, ROLE_INSPECTION_ADMIN]
                on_top: true
                icon:   '<i class="fa fa-check-circle-o"></i>'
            Deals:
                label: Deals
                items: [admin.branch.deal]
                roles: [ROLE_DEAL_READER, ROLE_DEAL_EDITOR, ROLE_DEAL_ADMIN]
                on_top: true
                icon:   '<i class="fa fa-list-ul"></i>'
            Valuations:
                label: Valuations
                items: [admin.valuation]
                roles: [ROLE_VALUATION_READER, ROLE_VALUATION_EDITOR, ROLE_VALUATION_ADMIN]
                icon:   '<i class="fa fa-usd"></i>'
                on_top: true
            Valuations Configurations:
                label: Valuations Configurations
                items: [admin.valuation.valuation_configuration]
                roles: [ROLE_VALUATION_CONFIGURATION_READER]
                icon:   '<i class="fa fa-cogs"></i>'
                on_top: true
            Branches:
                label: Branches
                items: [admin.branch, admin.branch.timing]
                roles: [ROLE_SUPER_ADMIN]
                icon:   '<i class="fa fa-building"></i>'
            Users:
                label: Users
                items: [admin.user]
                roles: [ROLE_SUPER_ADMIN]
                on_top: true
                icon:   '<i class="fa fa-user-circle-o"></i>'
            Vehicles:
                label: Vehicles
                items: [admin.vehicle.make, admin.vehicle.model, admin.vehicle.model_type]
                roles: [ROLE_SUPER_ADMIN]
                icon:   '<i class="fa fa-car"></i>'
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Appointments"]
                roles: [ROLE_ADMIN_BRANCH_APPOINTMENT_LIST]
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Inspections"]
                roles: [ROLE_ADMIN_BRANCH_INSPECTION_LIST]
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Deals"]
                roles: [ROLE_ADMIN_BRANCH_DEAL_LIST]
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Valuations"]
                roles: [ROLE_ADMIN_VALUATION_LIST]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Valuation Configuration"]
                roles: [ROLE_ADMIN_VALUATION_VALUATION_CONFIGURATION_LIST]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Branches"]
                roles: [ROLE_SUPER_ADMIN]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Users"]
                roles: [ROLE_SUPER_ADMIN]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Vehicles"]
                roles: [ROLE_SUPER_ADMIN]

    title: "WeBuyCars Admin"
    title_logo: /images/admin-logo.png
    persist_filters: true
    security:
        handler: sonata.admin.security.handler.role

        # acl security information
        information:
            GUEST: [VIEW, LIST]
            STAFF: [EDIT, LIST, CREATE]
            EDITOR: [OPERATOR, EXPORT]
            ADMIN: [MASTER]

        # permissions not related to an object instance and also to be available when objects do not exist
        # the DELETE admin permission means the user is allowed to batch delete objects
        admin_permissions: [CREATE, LIST, DELETE, UNDELETE, EXPORT, OPERATOR, MASTER]

        # permission related to the objects
        object_permissions: [VIEW, EDIT, DELETE, UNDELETE, OPERATOR, MASTER, OWNER]


services:
    admin.branch.appointment:
        class: Wbc\BranchBundle\Admin\AppointmentAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Appointment, WbcBranchBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Appointments, group: "Appointments" }

    admin.branch:
        class: Wbc\BranchBundle\Admin\BranchAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Branch, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Branches, group: "Branches" }

    admin.branch.timing:
        class: Wbc\BranchBundle\Admin\TimingAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Timing, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Branch Timings, group: "Branches" }

    admin.user:
        class: Wbc\UserBundle\Admin\UserAdmin
        arguments: [~, Wbc\UserBundle\Entity\User, WbcUserBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users, group: "Users" }

    admin.valuation:
        class: Wbc\ValuationBundle\Admin\ValuationAdmin
        arguments: [~, Wbc\ValuationBundle\Entity\Valuation, WbcValuationBundle:ValuationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Valuation, group: "Valuations"}

    admin.valuation.valuation_configuration:
        class: Wbc\ValuationBundle\Admin\ValuationConfigurationAdmin
        arguments: [~, Wbc\ValuationBundle\Entity\ValuationConfiguration, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Valuation Configuration, group: "Valuation Configuration"}

    admin.branch.inspection:
        class: Wbc\BranchBundle\Admin\InspectionAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Inspection, WbcBranchBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Inspection, group: "Inspections" }

    admin.branch.deal:
        class: Wbc\BranchBundle\Admin\DealAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Deal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Deal, group: "Deals" }

    admin.vehicle.make:
        class: Wbc\VehicleBundle\Admin\MakeAdmin
        arguments: [~, Wbc\VehicleBundle\Entity\Make, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Makes, group: "Vehicles" }
    admin.vehicle.model:
        class: Wbc\VehicleBundle\Admin\ModelAdmin
        arguments: [~, Wbc\VehicleBundle\Entity\Model, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Models, group: "Vehicles" }
    admin.vehicle.model_type:
        class: Wbc\VehicleBundle\Admin\ModelTypeAdmin
        arguments: [~, Wbc\VehicleBundle\Entity\ModelType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Trims, group: "Vehicles" }
