sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
sonata_admin:
    dashboard:
        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Appointments"]
                roles: [ROLE_BUYER]
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Inspections"]
                roles: [ROLE_BUYER]
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Deals"]
                roles: [ROLE_BUYER]
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Valuations"]
                roles: [ROLE_SUPER_ADMIN]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Branches"]
                roles: [ROLE_SUPER_ADMIN]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: ["Users"]
                roles: [ROLE_SUPER_ADMIN]

    title: "WeBuyCars Admin"
    title_logo: /images/admin-logo.png
    persist_filters: true

services:
    admin.branch.appointment:
        class: Wbc\BranchBundle\Admin\AppointmentAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Appointment, WbcBranchBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Appointments, group: "Appointments" }

    admin.branch:
        class: Wbc\BranchBundle\Admin\BranchAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Branch, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Branches, group: "Branches" }

    admin.branch.timing:
        class: Wbc\BranchBundle\Admin\TimingAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Timing, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Branch Timings, group: "Branches" }

    admin.branch.user:
        class: Wbc\UserBundle\Admin\UserAdmin
        arguments: [~, Wbc\UserBundle\Entity\User, WbcUserBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Users, group: "Users" }

    admin.valuation:
        class: Wbc\ValuationBundle\Admin\ValuationAdmin
        arguments: [~, Wbc\ValuationBundle\Entity\Valuation, WbcValuationBundle:ValuationAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Valuation, group: "Valuations"}

    admin.valuation.valuation_configuration:
        class: Wbc\ValuationBundle\Admin\ValuationConfigurationAdmin
        arguments: [~, Wbc\ValuationBundle\Entity\ValuationConfiguration, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Valuation Configuration, group: "Valuations"}

    admin.branch.inspection:
        class: Wbc\BranchBundle\Admin\InspectionAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Inspection, WbcBranchBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Inspection, group: "Inspections" }

    admin.branch.deal:
        class: Wbc\BranchBundle\Admin\DealAdmin
        arguments: [~, Wbc\BranchBundle\Entity\Deal, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Deal, group: "Deals" }

