services:
    static.parameter.repository:
        class: Wbc\StaticBundle\Repository\ParameterRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: ['Wbc\StaticBundle\Entity\Parameter']
        calls:
            - [ setCacheManager, ['@memcached'] ]
