services:
    wbc.branch.branch_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Wbc\BranchBundle\Entity\Branch

    wbc.branch.appointment_repository:
        class: Doctrine\ORM\EntityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Wbc\BranchBundle\Entity\Appointment
