services:
     wbc.utility.form.gender:
         class: Wbc\UtilityBundle\Form\GenderType
         tags:
            - { name: form.type, alias: wbc_utility_gender }

     wbc.utility.form.mobile_number:
         class: Wbc\UtilityBundle\Form\MobileNumberType
         tags:
            - { name: form.type, alias: wbc_utility_mobile_number }

     wbc.utility.form.language:
         class: Wbc\UtilityBundle\Form\LanguageType
         tags:
            - { name: form.type, alias: wbc_utility_language }

     wbc_utility_city:
         class: Wbc\UtilityBundle\Form\CityType
         arguments: ['@wbc.utility.model.city_list']
         tags:
            - { name: form.type, alias: wbc_utility_city }

     wbc.utility.model.city_list:
         class: Wbc\UtilityBundle\Model\City
         factory: [Wbc\UtilityBundle\Model\City, getCitiesList]
